# Generated by Django 5.1.15 on 2026-09-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workoutday_remove_monthlybudget_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
