# Generated by Django 5.1.15 on 2026-09-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailymeal_dailyworkoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='activity_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='biological_sex',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='current_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='goal_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height_cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_fat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_protein',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='target_water_ml',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='training_focus',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='training_frequency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
